# akshitsalwan@Akshits-MacBook-Air CodeMastery % git pull
# Updating 162b308..c15afac
# Fast-forward
#  .test/LoginPage.e2e.test.js                       |   235 +
#  .test/LoginPage.test.js                           |   188 +
#  .test/README.md                                   |   535 +++
#  .test/SignupPage.e2e.test.js                      |   338 ++
#  .test/SignupPage.test.js                          |   248 +
#  README.md                                         |    73 +
#  dist/assets/AdminPage-BnlLJHpg.js                 |     1 -
#  dist/assets/AdminPage-D50vT4WO.js                 |     1 +
#  dist/assets/CodeEditorPage-CW8Tq2cd.js            |    65 +
#  dist/assets/CodeEditorPage-DFqYN7cY.js            |    56 -
#  dist/assets/ContestsPage-5ntaRPWW.js              |     2 +
#  dist/assets/ContestsPage-Ds3d0Ep7.js              |     2 -
#  dist/assets/CreateContestPage-BHByanbo.js         |     6 -
#  dist/assets/CreateContestPage-C1O1Q6gU.js         |     6 +
#  dist/assets/InterviewerPanelPage-DmXkOZ5E.js      |     1 +
#  dist/assets/InterviewerPanelPage-yyzJYCRD.js      |     1 -
#  dist/assets/LeaderboardPage-BjGL8QgT.js           |     1 +
#  dist/assets/LeaderboardPage-CMoBDeWc.js           |     1 -
#  dist/assets/LearnersPlatformPage-CtLHIOZD.js      |     1 +
#  dist/assets/LearnersPlatformPage-DuxRaejD.js      |     1 -
#  dist/assets/LearnersPlatformTopicPage-4sxlN3PA.js |     1 +
#  dist/assets/LearnersPlatformTopicPage-CQgsXZNh.js |     1 -
#  dist/assets/TestBuilderPage-CDZJYOmq.js           |     3 +
#  dist/assets/TestBuilderPage-WqbROmNK.js           |     3 -
#  dist/assets/index-C2GemBdN.js                     |   330 --
#  dist/assets/index-D91aPuQk.css                    |     1 +
#  dist/assets/index-DbEiWhl1.css                    |     1 -
#  dist/assets/index-ccjM5gSQ.js                     |     3 +
#  dist/index.html                                   |    28 +-
#  jest-puppeteer.config.cjs                         |     8 +
#  jest.config.js                                    |    25 +
#  jest.e2e.config.cjs                               |    22 +
#  jest.setup.js                                     |    11 +
#  package-lock.json                                 | 17088 ++++++++++++++++++++++++++++++++++++++++++++++++------------------
#  package.json                                      |    18 +
#  server/controllers/problemController.js           |    30 +-
#  server/middleware/auth.js                         |    27 +-
#  server/routes/auth.js                             |    52 +-
#  server/routes/problems.js                         |     1 +
#  server/server.js                                  |     7 +-
#  server/services/geminiService.js                  |   166 +-
#  server/services/passwordResetService.js           |    52 +-
#  src/pages/CodeEditorPage.jsx                      |   171 +-
#  src/pages/LoginPage.jsx                           |     2 +-
#  src/pages/SignupPage.jsx                          |     2 +-
#  45 files changed, 14664 insertions(+), 5151 deletions(-)
#  create mode 100644 .test/LoginPage.e2e.test.js
#  create mode 100644 .test/LoginPage.test.js
#  create mode 100644 .test/README.md
#  create mode 100644 .test/SignupPage.e2e.test.js
#  create mode 100644 .test/SignupPage.test.js
#  delete mode 100644 dist/assets/AdminPage-BnlLJHpg.js
#  create mode 100644 dist/assets/AdminPage-D50vT4WO.js
#  create mode 100644 dist/assets/CodeEditorPage-CW8Tq2cd.js
#  delete mode 100644 dist/assets/CodeEditorPage-DFqYN7cY.js
#  create mode 100644 dist/assets/ContestsPage-5ntaRPWW.js
#  delete mode 100644 dist/assets/ContestsPage-Ds3d0Ep7.js
#  delete mode 100644 dist/assets/CreateContestPage-BHByanbo.js
#  create mode 100644 dist/assets/CreateContestPage-C1O1Q6gU.js
#  create mode 100644 dist/assets/InterviewerPanelPage-DmXkOZ5E.js
#  delete mode 100644 dist/assets/InterviewerPanelPage-yyzJYCRD.js
#  create mode 100644 dist/assets/LeaderboardPage-BjGL8QgT.js
#  delete mode 100644 dist/assets/LeaderboardPage-CMoBDeWc.js
#  create mode 100644 dist/assets/LearnersPlatformPage-CtLHIOZD.js
#  delete mode 100644 dist/assets/LearnersPlatformPage-DuxRaejD.js
#  create mode 100644 dist/assets/LearnersPlatformTopicPage-4sxlN3PA.js
#  delete mode 100644 dist/assets/LearnersPlatformTopicPage-CQgsXZNh.js
#  create mode 100644 dist/assets/TestBuilderPage-CDZJYOmq.js
#  delete mode 100644 dist/assets/TestBuilderPage-WqbROmNK.js
#  delete mode 100644 dist/assets/index-C2GemBdN.js
#  create mode 100644 dist/assets/index-D91aPuQk.css
#  delete mode 100644 dist/assets/index-DbEiWhl1.css
#  create mode 100644 dist/assets/index-ccjM5gSQ.js
#  create mode 100644 jest-puppeteer.config.cjs
#  create mode 100644 jest.config.js
#  create mode 100644 jest.e2e.config.cjs
#  create mode 100644 jest.setup.js